### ISSUE TITLE
Pubkey/Privkey size

### ISSUE THREAD

**Issue by cytadela8** [aeternity/elixir-wallet#101]
Currently Aewallet can generate keys that are shorter then 33bytes. That's due to the fact they are internally interpreted as number and begining zeros are truncated. It causes some errors in elixir-node, becouse we expect the key to be always 33bytes.

I discussed that with @thepiwo and the preferable solution would be to add leading zeros.

I'm not sure if this bug should be fixed in aewallet, but that's probably the best place to add the fix.

**Comment by thepiwo** [comment]
I guess we should add leading zeros

**Comment by cytadela8** [comment]
Correct. I fixed top comment.

**Comment by gspasov** [comment]
```elixir
iex(37)> p = fn -> for a <- 1..100000, do: to_string(a) end                                                      
#Function<20.99386804/0 in :erl_eval.expr/5>
iex(38)> l = for elem <- p.(), do: "M/" |> Kernel.<>(elem) |> Wallet.get_public_key() |> byte_size() |> inspect()
["33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33",
 "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33",
 "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33",
 "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", "33", ...]
iex(39)> Enum.all?(l, fn(x) -> x == "33" end)                                                                    
true
```

**Comment by cytadela8** [comment]
As I can't reproduce this bug I close the issue.
