### ISSUE TITLE
Fix generation of child public key from parent public key

### ISSUE THREAD

**Issue by gspasov** [aeternity/elixir-wallet#65]
[Here](https://bitcoin.stackexchange.com/questions/62533/key-derivation-in-hd-wallets-using-the-extended-private-key-vs-hardened-derivati) we can see how the child key derivation should work. Problem lies with the implementation of the Elliptic curve [Point addition](https://en.wikipedia.org/wiki/Elliptic_curve_point_multiplication#Point_addition)

More info on the Elliptic curve could be found [here](https://eng.paxos.com/blockchain-101-elliptic-curve-cryptography) for further help. The idea of taking the x and y points of the public key come from there.

So here I have some code, still it's not working as it should 
```elixir
serialized_pub_key = KeyPair.compress(parent_key)

    <<derived_key::256, child_chain::binary>> =
      :crypto.hmac(:sha512, key.chain_code,
        <<serialized_pub_key::binary, index::size(32)>>)

    {tweak, _} = :crypto.generate_key(:ecdh, :secp256k1, derived_key)

    ## MAGIC HAPPENS HERE !!!!

    <<_rest::8, x_par::256, y_par::256>> = parent_key
    <<_rest::8, x_tw::256, y_tw::256>> = tweak

    p = 115792089237316195423570985008687907853269984665640564039457584007908834671663
    h = (y_tw - y_par) / (x_tw - y_par)
    IO.inspect round(h)
    lambda = rem(h, p)

    x_r = rem((lambda*lambda - x_tw - x_par), p)
    y_r = rem((lambda*(x_tw - x_r) - y_tw), p)

    child_key = <<4::8, x_r::size(256), y_r::size(256)>> |> KeyPair.compress()
```

Java implementation could be found [here](https://github.com/bitsofproof/supernode/blob/1.1/api/src/main/java/com/bitsofproof/supernode/api/ExtendedKey.java#L304)

Ruby implementation could be found [here](https://github.com/GemHQ/money-tree/blob/master/lib/money-tree/node.rb#L93)

C implementation [here](https://github.com/bitcoin-core/secp256k1/blob/master/src/secp256k1.c#L477)

**Comment by gspasov** [comment]
For now, the best solution I've found is to copy the code from [this](https://github.com/cryptocoinjs/ecurve) javascript library to Elixir. It's the most understandable code that has the point addition functionality.

@thepiwo Any opinion?

**Comment by thepiwo** [comment]
Can you figure out what the difference is from their, to your implementation?

**Comment by gspasov** [comment]
I have no implementation of the Elliptic curve Point addition

**Comment by thepiwo** [comment]
oh yes sorry, you can try to translate the code to elixir, maybe as seperate library, as you see fit

**Comment by gspasov** [comment]
Finally I decided to use an erlang nif implementation of the secp256k1 Bitcoin library that has the functionality of point addition. Now after implementing it as dependency to make it work you need to install couple of things if you are missing them. 
Particularly: 
```sudo apt-get install autoconf autogen```
```sudo apt-get install libtool```
```sudo apt-get install libgmp3-dev```

This will be added to the README.md file as well
